### ISSUE TITLE
Building error in AukPageIndicatorContainer.swift / AutoCancellingTimer.swift

### ISSUE THREAD

**Issue by gadget00** [evgenyneu/Auk#35]
hi; your code is amazing and has helped me a lot.  But after updating to 2.1.5 through cocoapods, Im getting this errors during building:

![screen shot 2016-06-07 at 12 37 40 am](https://cloud.githubusercontent.com/assets/27822/15847029/203d06b8-2c48-11e6-9ecf-bf52c7e2d0a3.png)

I think it refers to the '#' symbol you are using in `#selector(...,` but I've never had any problem since I started using it so I have no idea if this is a change with the update.

I hope you can take a look at this soon, or at least see if there was a difference back in version 2.0.19, which was working perfectly to me.

Thanks for your great effort; hail to the Great Auk!

**Comment by gadget00** [comment]
I rolled back to 2.0.19 and again the project compiled correctly.  Better check that out

THanks again for your effort

**Comment by evgenyneu** [comment]
Hello @gadget00 (cool username), thanks for reporting. The compilation errors you saw were probably because of the new [`#selector` syntax](https://swift.org/blog/swift-2-2-new-features/) that use used since the version 2.1 of Auk. You were right to rollback to 2.0.19 version. Sorry I broke your app with this changed, I should have used the major version for this updated (3.0.0 instead of 2.1.0).

Just for other people who encounter similar problem, the setup instructions for previous versions of Swift are here: https://github.com/evgenyneu/Auk/wiki/Previous-versions

Thanks

**Comment by gadget00** [comment]
Hi evgenyneu,

I rolled back, and now I have this runtime error: `dyld: Library not loaded: @rpath/Auk.framework/Auk
  Referenced from:XXXXX   Reason: image not found`

This never happened to me. I installed Auk through Cocoapods, and tried to re-create the pods 4 times already, including using 'pod deintegrate' to totally eliminate Pods from my project and re-creating them again, and still get this error.

please help.

**Comment by evgenyneu** [comment]
Is this issue solved, @gadget00?

**Comment by gadget00** [comment]
Yes it is solved.  You can close it
